// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbieqzsm6RrzuX9Plx1eKc7uTJECP5ANo',
    appId: '1:56587948246:web:c936681b61d36f4af33977',
    messagingSenderId: '56587948246',
    projectId: 'chatapp-a2b40',
    authDomain: 'chatapp-a2b40.firebaseapp.com',
    storageBucket: 'chatapp-a2b40.firebasestorage.app',
    measurementId: 'G-F7B2P448V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqf0PidPB-lFJ2abSVCPhXqJiRefrpaP4',
    appId: '1:56587948246:android:5fcbba6bad3edd91f33977',
    messagingSenderId: '56587948246',
    projectId: 'chatapp-a2b40',
    storageBucket: 'chatapp-a2b40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbQHG5EMBLSoqDKc3f8QMilIPBBTdIt-Q',
    appId: '1:56587948246:ios:6796faaca750fca3f33977',
    messagingSenderId: '56587948246',
    projectId: 'chatapp-a2b40',
    storageBucket: 'chatapp-a2b40.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbQHG5EMBLSoqDKc3f8QMilIPBBTdIt-Q',
    appId: '1:56587948246:ios:6796faaca750fca3f33977',
    messagingSenderId: '56587948246',
    projectId: 'chatapp-a2b40',
    storageBucket: 'chatapp-a2b40.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbieqzsm6RrzuX9Plx1eKc7uTJECP5ANo',
    appId: '1:56587948246:web:513fcb963ae6f316f33977',
    messagingSenderId: '56587948246',
    projectId: 'chatapp-a2b40',
    authDomain: 'chatapp-a2b40.firebaseapp.com',
    storageBucket: 'chatapp-a2b40.firebasestorage.app',
    measurementId: 'G-PLWMCF4WSN',
  );
}
